### ISSUE TITLE
data classes

### ISSUE THREAD

**Issue by jeantuffier** [hyperoslo/android-playbook#27]
What do you think about the formatting for data classes ? Which one do you prefer ? 

``` kotlin
data class ProductColorBlock(val title: String, val description: String, val products: Array<Product>,
                                                val colors: Array<String>, val link: String)
```

vs

``` kotlin
data class ProductColorBlock(
        val title: String, 
        val description: String, 
        val products: Array<Product>,
        val colors: Array<String>, 
        val link: String
)
```

**Comment by jeantuffier** [comment]
I prefer the second one, I think It's a lot more easy to read

**Comment by sindrenm** [comment]
Definitely the last one. But in the case of smaller data classes with less properties inlining is fine:

``` kotlin
data class Point(val x: Int, val y: Int)
```

**Comment by jeantuffier** [comment]
Agreed then :) but let's wait a little bit for other comments before putting this as a rule in the README file

**Comment by sindrenm** [comment]
I think we've waited long enough, @jeantuffier. I'll make a PR. :+1:
